######################################################################
#
# File name : led_test_compile.do
# Created on: Tue Jan 15 17:53:31 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\bao\\FPGA\\modelsim\\xin\\win64\\vlib modelsim_lib/work
D:\\bao\\FPGA\\modelsim\\xin\\win64\\vlib modelsim_lib/msim

D:\\bao\\FPGA\\modelsim\\xin\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\bao\\FPGA\\modelsim\\xin\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\bao\\FPGA\\modelsim\\xin\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../my_vivado_test.srcs/sources_1/new/test.v" \


# compile glbl module
D:\\bao\\FPGA\\modelsim\\xin\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

