######################################################################
#
# File name : led_test_wave.do
# Created on: Tue Jan 15 17:53:33 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
