######################################################################
#
# File name : led_test_simulate.do
# Created on: Tue Jan 15 17:53:33 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.led_test xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {led_test_wave.do}

view wave
view structure
view signals

do {led_test.udo}

run 1000ns
