######################################################################
##
## Filename: sdram_top.udo
## Created on: Tue Aug 07 14:45:08 中国标准时间 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
