######################################################################
##
## Filename: sdram_model_plus.udo
## Created on: Mon Aug 06 19:05:22 中国标准时间 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
